name: Saludo usando variables y secretos
on: workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo variables
        run: echo "$SALUDO, ${{ vars.NOMBRE_COMPLETO }}. Hoy es $DIA_DE_SEMANA"
  saludo-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo secretos
        run: echo "$SALUDO, ${{ vars.NOMBRE_COMPLETO }}. Tu contraseña es ${{ secrets.CONTRASENA }}!"
